### ISSUE TITLE
Don't play FullMatchSports

### ISSUE THREAD

**Issue by ghost** [PhantomRaspberryBlower/repository.prb-entertainment-pack#1] opened 2019-09-28 18:11 UTC
Hi, I have problem to play "Formula 1 Replay" videos, but I found solution for:
https://github.com/PhantomRaspberryBlower/repository.prb-entertainment-pack/blob/8e5d5d9c23fc9203bd4742b5dfefad27c4592cb6/script.module.sportsreplay/lib/commontasks.py#L253

```
xbmc.Player().play(url+'|User-Agent=Mozilla', liz)
```
because if user-agent has `kodi` value, don't play

**Comment by PhantomRaspberryBlower** [comment] 2019-10-22 22:51
Hi, thanks for the heads-up. :) The problem is the website used to connect to the streams recently changed the way the streams are provided. So I'm currently looking at ways to connect to the new format, but this is proving to be tricky.
PS. Formula 1 Replay will be incorporated into the Sports Replay Addon, along with other sports.

**Comment by PhantomRaspberryBlower** [comment] 2019-12-07 11:45
@2small
Just to let you now, this addon is working again. I have created another addon called sports replay that will replace this addon. Try installing that instead. Enjoy :)

**Closed as completed by PhantomRaspberryBlower** 2019-12-07 11:45 UTC
